# SPDX-FileCopyrightText: 2026 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0
volumes:
  pg_data_17:
    driver: local

services:
  keycloak:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB_NAME=keycloakdb
      - KC_DB_URL=jdbc:postgresql://postgres/keycloakdb
      - KC_DB_USERNAME=keycloakdbuser
      - KC_DB_PASSWORD=keycloakdbpassword
    command: start-dev --import-realm
    volumes:
      - ./realms:/opt/keycloak/data/import:ro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: docker.io/postgres:17-alpine
    environment:
      - POSTGRES_USER=keycloakdbuser
      - POSTGRES_PASSWORD=keycloakdbpassword
      - POSTGRES_DB=keycloakdb
    volumes:
      - pg_data_17:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "keycloakdbuser", "-d", "keycloakdb"]
